# This is a basic workflow to help you get started with Actions

name: PDF

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: html to pdf
        uses: misaelnieto/web_to_pdf_action@master
        with:
          webPageURL: https://thomashighbaugh.github.io/resume/
          outputFile: resume.pdf
          usePuppeteer: true
          pdfOptions: '{"format": "Letter", "margin": {"top": "0", "left": "0", "right": "0", "bottom": "0"}}'
