name: site-pdf
on:
  push:
    branches:
      - master
    paths:
      - "index.html"

jobs:
  build:
    runs-on: ubuntu-latest

    name: Generate PDF
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Create "/pdf" directory
        run: mkdir pdf && sudo chmod 777 pdf

      - name: Build PDF
        run: docker run --rm -t -v `pwd`:/pdf -v ~:/home/user Thomashighbaugh/resume resume/index.html pdf/thomas-leon-highbaugh.pdf

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKE }}
          publish_dir: ./pdf
          publish_branch: pdf
          keep_files: true
